---
- name: Threat Intelligence Gathering and Response Playbook
  hosts: localhost
  connection: local
  vars:
    ip_to_check: "8.8.8.8"

  tasks:
    - name: Ensure blocklist is clean before run
      ansible.builtin.copy:
        content: ""
        dest: ../blocklist.txt

    - name: Run AbuseIPDB enrichment script
      command: "python3 ../app/scripts/check_abuseipdb.py {{ ip_to_check }}"
      register: abuse_raw_result
      changed_when: false

    - name: Parse AbuseIPDB JSON output
      set_fact:
        abuse_result: "{{ abuse_raw_result.stdout | from_json }}"

    - name: Run VirusTotal enrichment script
      command: "python3 ../app/scripts/check_virustotal.py {{ ip_to_check }}"
      register: vt_raw_result
      changed_when: false

    - name: Parse VirusTotal JSON output
      set_fact:
        vt_result: "{{ vt_raw_result.stdout | from_json }}"

    - name: Generate Markdown report from template
      template:
        src: ./templates/report.md.j2
        dest: ../report.md

    - name: Add malicious IP to blocklist if abuse score is high
      ansible.builtin.lineinfile:
        path: ../blocklist.txt
        line: "{{ ip_to_check }}"
      when: abuse_result.abuseConfidenceScore | int > 80